---
new_page_extension: md
auto_deploy: false
admin_path: ''
webhook_url: 
sections:
- type: directory
  path: content/blog
  label: Blog
  create: all
  match: "**/*"
  templates:
  - post
- type: directory
  path: content/books
  label: Books
  create: all
  match: "**/*"
upload_dir: uploads
public_path: "/uploads"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
build:
  preview_output_directory: output
  install_dependencies_command: pip install -r requirements.txt
  preview_docker_image: python:3
  mount_path: "/usr/src/app"
  instant_preview_command: pelican content
